//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeITDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string OriginalFileName { get; set; }
        public System.DateTime OriginalFileDate { get; set; }
        public string NewFileName { get; set; }
        public string MD5Checksum { get; set; }
        public string OriginalFileLocation { get; set; }
        public string NewFileLocation { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public bool IsArchived { get; set; }
        public string Note { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Resolution { get; set; }
        public Nullable<bool> IsCloudFileSystem { get; set; }
        public Nullable<int> UploadId { get; set; }
    }
}
